version: "3.3"
services:
  tandb-gateway:
    build:
      ./tandb-gateway
    env_file:
      - tandb-gateway/variables.env
    ports:
      - "9080:9080"
    networks:
      - backend
    command: ["/application/start.sh"]

  tandb-auth:
    build:
      ./tandb-auth
    env_file:
      - tandb-auth/variables.env
    ports:
      - "9081:9081"
    networks:
      - backend
    command: ["/application/start.sh"]

  tandb-vote:
    build:
      ./tandb-vote
    env_file:
      - tandb-vote/variables.env
    ports:
      - "9082:9082"
    networks:
      - backend
    command: ["/application/start.sh"]

  postgres-db:
    image: postgres:12.1-alpine
    restart: always
    networks:
        - backend
    volumes:
        - ./db-data:/var/lib/postgresql/data
        - ./tandb-auth/init-db.sql:/docker-entrypoint-initdb.d/init-tandb-auth.sql
        - ./tandb-vote/init-db.sql:/docker-entrypoint-initdb.d/init-tandb-vote.sql
    ports:
        - "5432:5432"

  nginx:
    restart: always
    image: nginx:1.15.2-alpine
    networks:
        - backend
    ports:
        - 80:80
    restart: "always"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/static:/var/www/static

networks:
  backend:
