version: "3.3"
services:
  tandb-gateway:
    build:
      ./tandb-gateway
    restart: always
    volumes:
      - ./tandb-gateway/src:/application/src
    command: ["/application/dev.sh"]

  tandb-auth:
    build:
      ./tandb-auth
    restart: always
    volumes:
      - ./tandb-auth/src:/application/src
    command: ["/application/dev.sh"]
    entrypoint: ["/application/wait-for-it.sh", "-s" , "-t", "60", "postgres-db:5432", "--"]

  tandb-vote:
    build:
      ./tandb-vote
    restart: always
    volumes:
      - ./tandb-vote/src:/application/src
    command: ["/application/dev.sh"]
    entrypoint: ["/application/wait-for-it.sh", "-s" , "-t", "60", "postgres-db:5432", "--"]

networks:
  backend:
